### ISSUE TITLE
Create updated content

### ISSUE THREAD

**Issue by rhumaric** [rhumaric/romaricpascal.is#45]
- [x] *Page description*
  - [x] Lettering
  - [x] Logo & Brands
  - [x] Prints & Illustrations
  - [x] Tshirts & Merch
  - [x] Web
  - [x] Artworks
  - [x] Blog
  - [x] Contact
  - [x] Testimonials
- [x] *Projects*
  - [x] Simpleshop
    - [x] Link to live website
    - [x] Move some writing to behind the scene
  - [x] TaskFight logo
    - [x] Link to live website
    - [x] Move some writing to behind the scene
  - [x] D2D
    - [x] Link to live website
    - [x] Move some writing to behind the scene
    - [x] Fix image of final branding
  - [x] Up your game
    - [x] Full write-up
    - [x] Links
    - [x] ~Improved mock-ups~ #46 
    - [x] Process shots
  - [x] Face your fears
    - [x] Full write-up
    - [x] Links
    - [x] ~Improved mock-ups~ #46 
    - [x] Process shots
  - [x] Big dreams
    - [x] Full write-up
    - [x] Links
    - [x] ~Improved mock-ups~ #46 
    - [x] Process shots
  - [x] Make your own magic
    - [x] Full write-up
    - [x] Links
    - [x] Improved mock-ups
    - [x] Process shots
  - [x] Letters say more
    - [x] Full write-up
    - [x] Links
    - [x] Improved mock-ups
    - [x] Process shots
  - [x] Brain, you have one, use it
    - [x] Full write-up
    - [x] Links
    - [x] Improved mock-ups
    - [x] Process shots
- [x] *Artworks*
  - [x] "Available in shop" links
